
name: Issue to Project
on:
  issues:
    types: [opened, labeled]

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@main
        id: addItem
        with:
          project-url: https://github.com/orgs/OpenPecha/projects/58
          github-token: ${{ secrets.GH_PROJECT_TOKEN }}
          labeled: bug, feedbucket
          label-operator: OR
